extends: cheminfo

env:
  browser: true
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-var: error
  no-multi-spaces: off
  import/no-cycle: off 

settings:
  import/core-modules: [ test ]
